{
    'name': 'Custom List Column Width',
    'version': '19.0.29.1.1',
    'summary': 'Branding SOM, anchos de columnas, Búsqueda Global y Centro de Actividades',
    'category': 'Technical',
    'author': 'Alphaqueb Consulting SAS',
    'depends': ['web', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/som_activity_hub_security.xml',
        'data/som_activity_kinds.xml',
        'views/som_branding_templates.xml',
        'views/som_activity_hub_views.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'assets': {
        'web._assets_primary_variables': [
            ('prepend', 'theme_list_modern/static/src/scss/som_colors_variables.scss'),
        ],
        'web.assets_frontend': [
            'theme_list_modern/static/src/scss/som_colors_frontend.scss',
        ],
        'web.assets_backend': [
            'theme_list_modern/static/src/scss/som_colors_backend.scss',
            'theme_list_modern/static/src/css/list_modern.scss',
            'theme_list_modern/static/src/js/csrf_recovery.js',
            'theme_list_modern/static/src/js/list_renderer_patch.js',
            'theme_list_modern/static/src/js/uppercase_inputs.js',
            'theme_list_modern/static/src/global_search/global_search.scss',
            'theme_list_modern/static/src/scss/home_menu_mobile.scss',
            'theme_list_modern/static/src/global_search/global_search.xml',
            'theme_list_modern/static/src/global_search/global_search.js',
            'theme_list_modern/static/src/activity_hub/activity_hub.scss',
            'theme_list_modern/static/src/activity_hub/activity_hub.xml',
            'theme_list_modern/static/src/activity_hub/activity_hub.js',
            'theme_list_modern/static/src/activity_hub/activity_systray_sync.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}